// final/web/src/components/ReportInline.vue
<template>
  <template v-for="(token, index) in tokens" :key="index">
    <a v-if="token.type === 'citation'" :href="`#research-source-${token.sourceId}`" class="citation-link" :aria-label="`查看来源 ${token.sourceId}`" @click.prevent="$emit('citation', token.sourceId)">{{ token.text }}</a>
    <a v-else-if="token.type === 'link'" :href="token.href" target="_blank" rel="noopener noreferrer">{{ token.text }}</a>
    <strong v-else-if="token.type === 'strong'">{{ token.text }}</strong>
    <em v-else-if="token.type === 'em'">{{ token.text }}</em>
    <code v-else-if="token.type === 'code'">{{ token.text }}</code>
    <span v-else>{{ token.text }}</span>
  </template>
</template>
<script setup>
import { computed } from 'vue'
import { reportInlineTokens } from '../utils/research'
const props = defineProps({ text: { type: String, default: '' }, sources: { type: Array, default: () => [] }, references: { type: Array, default: () => [] } })
defineEmits(['citation'])
const tokens = computed(() => reportInlineTokens(props.text, props.sources, props.references))
</script>

// final/web/src/components/ReportInline.tsx
import { reportInlineTokens } from '../utils/research'

// 行内渲染：引用、加粗、斜体、行内代码、安全链接。只产出 React 节点，绝不产出 HTML。
export default function ReportInline(props: {
  text: string
  sources: any[]
  references: any[]
  onCitation: (sourceId: string) => void
}) {
  const tokens = reportInlineTokens(props.text, props.sources, props.references)
  return (
    <>
      {tokens.map((token, index) => {
        if (token.type === 'citation') {
          return (
            <a
              key={index}
              href={`#research-source-${token.sourceId}`}
              className="citation-link"
              aria-label={`查看来源 ${token.sourceId}`}
              onClick={e => { e.preventDefault(); props.onCitation(token.sourceId) }}
            >
              {token.text}
            </a>
          )
        }
        if (token.type === 'link') return <a key={index} href={token.href} target="_blank" rel="noopener noreferrer">{token.text}</a>
        if (token.type === 'strong') return <strong key={index}>{token.text}</strong>
        if (token.type === 'em') return <em key={index}>{token.text}</em>
        if (token.type === 'code') return <code key={index}>{token.text}</code>
        return <span key={index}>{token.text}</span>
      })}
    </>
  )
}
